export const skills = [
  {
    name: "React Js",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/2/react-of56d29pe4h55iptu3crb.png/react-2uh0qk5jwsgxiiribs5ox.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Next Js",
    icon: "https://www.vectorlogo.zone/logos/nextjs/nextjs-icon.svg",
    height: "8",
    width: "8",
  },
  {
    name: "Tailwind Css",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/4/tailwindcss-icon-lxvdm2ckbakronpli3lie.png/tailwindcss-icon-w2935uwocqtqvv7q2q257.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Node.js",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/2/nodejs-j4c0hwu1qmirh64mynjuz.png/nodejs-0g7vrhqizuhwkx0tucqkyb.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Typescript",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/5/typescript-icon-72zw2qe1mom0nafkd5pj6n.png/typescript-icon-lks16d1xu9b9qyidink7t.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Java",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/4/java-3l83r8hh7v5yhem0n2e1d.png/java-uny7np2dj70tb7u5at0ko.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Golang",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/3/go-l23r2618wcifby7p6jj7f4.png/go-szegm1wzik1647p3zhlms.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Mongo DB",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/4/mongodb-icon-qfb2w72fsgmue21n54x2ar.png/mongodb-icon-tzouctvl9mlat5c2vx39sg.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Prisma",
    icon: "https://prismalens.vercel.app/header/logo-white.svg",
    height: "15",
    width: "15",
  },
  {
    name: "PostgreSQL",
    icon: "https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg",
    height: "8",
    width: "8",
  },
  {
    name: "Google Gemini",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/3/google-gemini-924j3051o55m98g4rwehj.png/google-gemini-fjwerd7ldxwt4c010vyoh.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Vercel AI SDK",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/5/vercel-icon-1e44161oavq1mzuypoj9i7.png/vercel-icon-orebx5wd0vr5kk8w161dla.png?_a=DAJFJtWIZAAC",
    height: "10",
    width: "10",
  },
  {
    name: "AWS",
    icon: "https://raw.githubusercontent.com/devicons/devicon/master/icons/amazonwebservices/amazonwebservices-original-wordmark.svg",
    height: "8",
    width: "8",
  },
  {
    name: "Docker",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/3/docker-icon-odll06b1fn8uy81gdxmj9o.png/docker-icon-qsxg85w6v7scr4udgmluk.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Kubernetes",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/4/kubernetes-s8jwn3vs1hszcbaz6pqu7b.png/kubernetes-oije5l2tm8efxygf8ozhe.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "CI/CD",
    icon: "https://www.vectorlogo.zone/logos/jenkins/jenkins-icon.svg",
    height: "8",
    width: "8",
  },
  {
    name: "Turborepo",
    icon: "https://turbo.build/images/docs/repo/repo-hero-logo-dark.svg",
    height: "10",
    width: "10",
  },
  {
    name: "Supabase",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/4/supabase-icon-kpjasdqlnu8exakst6f44r.png/supabase-icon-5uqgeeqeknngv9las8zeef.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Websockets",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/5/websocket-w02xh571b3sxzooa60n1.png/websocket-16wzrfp0ko22h8s0km8xcb.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Redis",
    icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/2/redis-y590aw1nivh089zznjv43zu.png/redis-dzuksy8u5fiwy59bvnw4pp.png?_a=DAJFJtWIZAAC",
    height: "8",
    width: "8",
  },
  {
    name: "Solana",
    icon: "https://cryptologos.cc/logos/solana-sol-logo.svg",
    height: "8",
    width: "8",
  },
];
